LOAD DATA INFILE 'C:/Users/rafael.anjos/Desktop/DDA_Discovery/arquivo.csv'
INTO TABLE dda_find_notfind
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(
    IMPORTACAO,
    @IMPORTADO_EM,
    ENCONTRADO,
    DOCUMENTO_TITULO,
    @VALOR_DOCUMENTO,
    @VENCIMENTO,
    CPF_CNPJ_DOC_DDA,
    FORNECEDOR_EMISSOR,
    NROEMPRESA,
    @EMITIDO_EM,
    CODIGO_BARRAS,
    FINALIZADO,
    TIPOVINCULO,
    USUALTERACAO,
    USUIMPORTACAO
)
SET
    IMPORTADO_EM = STR_TO_DATE(@IMPORTADO_EM, '%d/%m/%Y'),
    VENCIMENTO = STR_TO_DATE(@VENCIMENTO, '%d/%m/%Y'),
    EMITIDO_EM = STR_TO_DATE(@EMITIDO_EM, '%d/%m/%Y'),
    VALOR_DOCUMENTO = REPLACE(@VALOR_DOCUMENTO, ',', '.');
