-- Imnportação de arquivos de dados direto de um arquivo csv
LOAD DATA INFILE 'C:/Users/rafael.anjos/Desktop/DDA_Discovery/arquivo.csv'
INTO TABLE dda_find_notfind
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(
    IMPORTACAO,
    IMPORTADO_EM,
    ENCONTRADO,
    DOCUMENTO_TITULO,
    VALOR_DOCUMENTO,
    VENCIMENTO,
    CPF_CNPJ_DOC_DDA,
    FORNECEDOR_EMISSOR,
    NROEMPRESA,
    EMITIDO_EM,
    CODIGO_BARRAS,
    FINALIZADO,
    TIPOVINCULO,
    USUALTERACAO,
    USUIMPORTACAO
);
-- NÃO TÃO EFICIENTE, EM PRIMEIRO TESTES LIMITOU 3403 LINHAS EM 1700
LOAD DATA INFILE 'C:/Users/rafael.anjos/Desktop/DDA_Discovery/arquivo.csv'
INTO TABLE dda_find_notfind
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(
    IMPORTACAO,
    @IMPORTADO_EM,
    ENCONTRADO,
    DOCUMENTO_TITULO,
    @VALOR_DOCUMENTO,
    @VENCIMENTO,
    CPF_CNPJ_DOC_DDA,
    FORNECEDOR_EMISSOR,
    NROEMPRESA,
    @EMITIDO_EM,
    CODIGO_BARRAS,
    FINALIZADO,
    TIPOVINCULO,
    USUALTERACAO,
    USUIMPORTACAO
)
SET
    IMPORTADO_EM = STR_TO_DATE(@IMPORTADO_EM, '%d/%m/%Y'),
    VENCIMENTO = STR_TO_DATE(@VENCIMENTO, '%d/%m/%Y'),
    EMITIDO_EM = STR_TO_DATE(@EMITIDO_EM, '%d/%m/%Y'),
    VALOR_DOCUMENTO = REPLACE(@VALOR_DOCUMENTO, ',', '.');

-- CRIAÇÃO DA TABELA PARA OS SCRIPTS ACIMA
CREATE TABLE dda_find_notfind (
    id INT AUTO_INCREMENT PRIMARY KEY,

    IMPORTACAO VARCHAR(255),
    
    IMPORTADO_EM DATE,
    
    ENCONTRADO VARCHAR(10),
    
    DOCUMENTO_TITULO VARCHAR(50),
    
    VALOR_DOCUMENTO DECIMAL(15,2),
    
    VENCIMENTO DATE,
    
    CPF_CNPJ_DOC_DDA VARCHAR(30),
    
    FORNECEDOR_EMISSOR VARCHAR(255),
    
    NROEMPRESA INT,
    
    EMITIDO_EM DATE,
    
    CODIGO_BARRAS VARCHAR(100),
    
    FINALIZADO CHAR(1),
    
    TIPOVINCULO VARCHAR(50),
    
    USUALTERACAO VARCHAR(100),
    
    USUIMPORTACAO VARCHAR(100)
);
